version: '3'

services:
  web:
    build: ./web
    container_name: web
    environment:
      -  CHOKIDAR_USEPOLLING=true
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
      - "24678:24678"
    working_dir: /web/webapp-learn
    command: /bin/sh -c "npm install && npm run dev"
  db:
    image: mysql:8.0.33
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./db/mysql:/var/lib/mysql
  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./api:/go/src
    working_dir: /go/src
    command: /bin/sh -c "go mod tidy && go run main.go"
